<?php
/*	Author		: Puranjan.
**	Date		: 14-05-2018
**	Description	: Core Framework Files.
**	Note		: Please do not edit this file unless you are absolutely sure about what you are doing.
**	scriptClass	: admin/Controller.
**	Type		: Website Template Module Extension Defination
*/
class ControllerEventTheme extends Controller {
	public function index(&$view, &$data) {
		// This is only here for compatibility with old templates
		if (substr($view, -4) == '.tpl') {
			$view = substr($view, 0, -4);
		}
	}
}
