/*	Initial Author		: Puranjan.
**	Date				: 23-05-2018
**	Description			: Core Framework Files.
**	Note				: Please do not edit this file unless you are absolutely sure about what you are doing.
**	scriptClass			: admin/Controller.
**	Type				: Reporting Module. NO DATA.
**	Developer			: Puranjan Gaur.
**	TEAM				: Backend Team.
*/


This file was made for Debugging purpose only. Some functionality can be added later.