<?php
/*	Initial Author		: Puranjan.
**	Date				: 24-03-2018
**	Description			: Core Framework Files. DATABASE INTERFACE.
**	Note				: Please do not edit this file unless you are absolutely sure about what you are doing.
**	scriptClass			: admin/Controller.
**	Type				: CONNECTION, SESSION & ADMIN START-UP Module.
**	scriptDescription	: This Script initialize the SECURE Admin Session and connection with the DataBase.
**	Developer			: Puranjan Gaur.
**	TEAM				: Backend Team.
*/
class ControllerStartupEvent extends Controller {
	public function index() {
		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "event` WHERE `trigger` LIKE 'admin/%' ORDER BY `event_id` ASC");
		
		foreach ($query->rows as $result) {
			$this->event->register(substr($result['trigger'], strpos($result['trigger'], '/') + 1), new Action($result['action']));
		}
	}
}