<?php
/*	Initial Author		: Puranjan.
**	Date				: 24-03-2018
**	Description			: Core Framework Files. DATABASE INTERFACE.
**	Note				: Please do not edit this file unless you are absolutely sure about what you are doing.
**	scriptClass			: admin/Controller.
**	Type				: CONNECTION, SESSION & ADMIN START-UP Module.
**	scriptDescription	: This Script initialize the SECURE Admin Session and connection with the DataBase.
**	Developer			: Puranjan Gaur.
**	TEAM				: Backend Team.
*/
class ControllerStartupSass extends Controller {
	public function index() {
		$file = DIR_APPLICATION . 'view/stylesheet/bootstrap.css';

		if (!is_file($file)) {
			$scss = new Scssc();
			$scss->setImportPaths(DIR_APPLICATION . 'view/stylesheet/sass/');

			$output = $scss->compile('@import "_bootstrap.scss"');

			$handle = fopen($file, 'w');

			flock($handle, LOCK_EX);

			fwrite($handle, $output);

			fflush($handle);

			flock($handle, LOCK_UN);

			fclose($handle);
		}
	}
}
