<?php
/*	Author		: Puranjan.
**	Date		: 20-05-2018
**	Description	: Core Framework Files.
**	Note		: Please do not edit this file unless you are absolutely sure about what you are doing.
**	scriptClass	: admin/Controller.
**	Type		: openbay Modules. USELESS. Just for Debugging.
**	Developer	: Puranjan Gaur.
*/
class ControllerOpenbayEtsyShop extends Controller {
	public function getSections() {
		$response = $this->openbay->etsy->call('v1/etsy/shop/getSections/', 'GET');

		$this->response->addHeader('Content-Type: application/json');
		return $this->response->setOutput(json_encode($response));
	}
}