<?php

/*	Author		: Puranjan.
**	Date		: 12-05-2018
**	Description	: Core Framework Files.
**	Note		: Please do not edit this file unless you are absolutely sure about what you are doing.
**	scriptClass	: NONE.
**	Type		: EMPTY
*/
